### ISSUE TITLE
Traffic.create incorrect acid check

### ISSUE THREAD

**Issue by euvl** [ethertricity/bluesky#10]
In Traffic.create these lines seem to be confusing to me:
```python
def create(self, acid=None, actype="B744", aclat=None,
               aclon=None, achdg=None, acalt=None, casmach=None):

        if self.id.count(acid.upper()) > 0:
            return False, acid + " already exists."  

        if acid is None or acid == "*":
            acid = "KL204"
       ...
```

First acid.upper() is called assuming that the value is of a `basestring` type, where function notation says `acid=None`. And after that there is a check `acid is None`. 

I think the logical flow is wrong.

**Comment by jooste** [comment]
Addressed in 61d044b (main version).
