### ISSUE TITLE
cmdstack clearing does not work

### ISSUE THREAD

**Issue by miklosduma** [ethertricity/bluesky#14]
Running BlueSky raises an exception: `list object has no attribute clear`

In `stack.py` (line 1203) you may want to replace `cmdstack.clear()` with sg that clears a list.  (cmdstack is a list, clear method is for dictionaries only)

Keep up the great work!

**Comment by jooste** [comment]
Ah, I see now. list.clear() is available only from python 3.3 and up :)

**Comment by miklosduma** [comment]
Indeed it is, I did not know that. A pity it is not accessible from the __future__ module like the new print function :)

**Comment by jooste** [comment]
Indeed. It looks a lot more readable with a .clear() method than with del [:]

**Comment by reube** [comment]
This is now fixed upstream.  Closing.
