### ISSUE TITLE
TCP connection to simulation is one-way only

### ISSUE THREAD

**Issue by jacobythwaites** [ethertricity/bluesky#4]
Please see https://github.com/ProfHoekstra/bluesky/issues/94

**Comment by reube** [comment]
The tcp socket for OpenGL console is created in `BlueSky_qtgl`.py with `gui.win.console.stack` assigned as the handler.  
`gui.win` corresponds to an instantiation of `blueky.ui.qtgl.mainwindow.MainWindow()`.  
The `console` attribute within `MainWindow()` is set according to a config file: `bluesky/data/graphics/mainwindow` viz: `<widget class="Console" name="console" native="true">` and `<class>Console</class><header location="global">bluesky/ui/qtgl/console</header>`.  
`gui.win.console` is thus an instantiation of `bluesky.ui.qtgl.console.Console()`
`gui.win.console.stack` is a member function of this class.  This function handles commands coming off the socket for the OpenGL implementation.

**Comment by reube** [comment]
When output from a command is to be echoed back to the GUI, an `echo()` function in `bluesky.sim.qtgl.screenio` is called.  For example, in `stack.py`: `bs.scr.echo("Syntax error: Too few arguments")`.
`screenio.echo()` calls `sendEvent()` on the node manager.  This in turn sends the event back to the GUI console, a.k.a. `bluesky.sim.qtgl.mainmanager`, to be processed by the function: `receiveFromNodes()`
It is at this point that we may also send the generated output from commands to the client via the appropriate tcp connection.

**Comment by reube** [comment]
Example output with fix:
```
>telnet localhost 8888
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```
```
AIRPORT EGKK
Info on EGKK:
GATWICK
is a large airport at:
N51'08'52.0"  W000'11'24.0"
Elevation: 202 ft 
in United Kingdom (uk)
Runways: 08R, 26L, 26R, 08L
ok.
```
