### ISSUE TITLE
Determine key refactoring and general tidying improvements and apply

### ISSUE THREAD

**Issue by reube** [ethertricity/bluesky#6]
* Instantiation of singleton classes
e.g. `bluesky.traf.traffic.Traffic` to be created in `bluesky/__init__.py` as `traf`, yielding: `bluesky.traf` for the singleton `Traffic` object.
* Creation, Extension, Use of dynamic numpy arrays is messy.
* PEP8, Pylint, e.g. capitalised function names, assignment syntax, enumerated types, spacing etc
* Constant literal definitions should replace hard-coding of constant values through code - should be CAPATILIZED too

**Comment by euvl** [comment]
Hey, if you are planning to work on this issue today (or weekends) could please use `refactoring` branch? I've done some basic steps there (PEPed and refactored pilot and traffic files, started moving out singleton declarations to __init__, etc) 

Thanks

**Comment by reube** [comment]
Superseded by new work effort.  Closed.
